# Generated by Django 5.0.4 on 2024-04-24 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be 3 to 10 characters and contain only letters and numbers.', regex='^\\w{3,10}$')])),
                ('password', models.PositiveIntegerField(error_messages={'maxLength': 'Password cannot be more than 6 digits'}, max_length=6)),
            ],
        ),
    ]
